server:
  port: 8003
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: software-service
  config:
    api-endpoints:
      software-url: http://localhost:8003/api/task

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/job_tracking_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect