server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: admin-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/job_tracking_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


software-service-url: http://localhost:8500/api/task
marketing-service-url: http://localhost:8500/api/campaign
hr-service-url: http://localhost:8500/api/user
auth-service-url: http://localhost:8500/api/auth